title: Md. Rahat Ansari
logo: assets/img/avatar.png
description: Full-Stack Web Developer and AI Engineer with expertise in building AI-driven web applications, computer vision, and security assessments and penetration testing.
#show_downloads: true
theme: jekyll-theme-minimal
